# Generated by Django 4.2.5 on 2024-04-05 10:27

from django.db import migrations
from users.models import UserProfile
from django.contrib.auth.models import User

def create_user_profiles(apps, schema_editor):
    for user in User.objects.all():
        if not hasattr(user, 'userprofile'):
            UserProfile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user'),  # Replace 'previous_migration' with the name of the previous migration
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]
