# Generated by Django 4.2.5 on 2024-04-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20240405_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='userpics'),
        ),
    ]
