# Generated by Django 4.2.5 on 2025-09-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_changed',
            field=models.BooleanField(default=False, help_text='Indicates if user has changed their initial password'),
        ),
    ]
