# Generated by Django 4.2.5 on 2024-02-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParishRestructure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
    ]
