# Generated by Django 4.2.5 on 2024-02-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ParishRestructure', '0002_location_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
    ]
