# Generated by Django 4.2.5 on 2024-02-22 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParishRestructure', '0004_parishregistration_alter_parish_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParishDirectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('register_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParishRestructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParishRestructure.location')),
                ('parish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParishRestructure.parishdirectory')),
            ],
        ),
        migrations.RemoveField(
            model_name='parishregistration',
            name='address',
        ),
        migrations.RemoveField(
            model_name='parishregistration',
            name='name',
        ),
        migrations.AlterField(
            model_name='parishregistration',
            name='date_of_establishment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Parish',
        ),
        migrations.AddField(
            model_name='parishregistration',
            name='parish',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParishRestructure.parishdirectory'),
        ),
    ]
