# Generated by Django 4.2.5 on 2024-02-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParishRestructure', '0005_parishdirectory_parishrestructure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parishregistration',
            name='application_for_registration',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='parishregistration',
            name='approval_from_government_diaspora',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='parishregistration',
            name='building_plan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='parishregistration',
            name='original_receipt_of_land',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='parishregistration',
            name='original_survey_plan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='parishregistration',
            name='parish_picture',
            field=models.ImageField(blank=True, default='static/assets/img/User/circled_user_male_skin_type_5_480px.png', null=True, upload_to='ParishRestructure/parish_pic'),
        ),
        migrations.AddField(
            model_name='parishregistration',
            name='passport_photograph',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='parishregistration',
            name='payment_proof_of_auditorium',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='parishregistration',
            name='sworn_affidavit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
