# Generated by Django 4.2.5 on 2024-03-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParishRestructure', '0006_parishregistration_application_for_registration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='level',
            field=models.CharField(choices=[('continent', 'Continent'), ('diocese', 'Diocese'), ('region', 'Region'), ('state', 'State'), ('area', 'Area'), ('district', 'District'), ('circuit', 'Circuit'), ('parish', 'Parish')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parishregistration',
            name='application_for_registration',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parishregistration',
            name='approval_from_government_diaspora',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parishregistration',
            name='building_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parishregistration',
            name='original_receipt_of_land',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parishregistration',
            name='original_survey_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parishregistration',
            name='parish_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ParishRestructure/parish_pic'),
        ),
        migrations.AlterField(
            model_name='parishregistration',
            name='passport_photograph',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parishregistration',
            name='payment_proof_of_auditorium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parishregistration',
            name='sworn_affidavit',
            field=models.BooleanField(default=False),
        ),
    ]
