# Generated by Django 4.2.5 on 2024-03-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParishRestructure', '0007_alter_location_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishregistration',
            name='parish_picture',
            field=models.ImageField(blank=True, null=True, upload_to='parish_pic'),
        ),
    ]
