# Generated by Django 4.2.5 on 2024-03-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParishRestructure', '0008_alter_parishregistration_parish_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishregistration',
            name='parish_picture',
            field=models.ImageField(blank=True, default='parish_pic/default.jpg', null=True, upload_to='parish_pic'),
        ),
    ]
