# Generated by Django 4.2.5 on 2024-04-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParishRestructure', '0009_alter_parishregistration_parish_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='level',
            field=models.CharField(choices=[('continent', 'Continent'), ('diocese', 'Diocese'), ('archdiocese', 'Arch Diocese'), ('region', 'Region'), ('state', 'State'), ('area', 'Area'), ('district', 'District'), ('specialdistrict', 'Special District'), ('circuit', 'Circuit'), ('parish', 'Parish')], max_length=20),
        ),
    ]
