# Generated by Django 4.2.5 on 2024-09-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParishRestructure', '0010_alter_location_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parishdirectory',
            name='register_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
