# Generated by Django 4.2.5 on 2025-10-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParishRestructure', '0011_alter_parishdirectory_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='level',
            field=models.CharField(choices=[('continent', 'Continent'), ('diocese', 'Diocese'), ('archdiocese', 'Arch Diocese'), ('region', 'Region'), ('state', 'State'), ('division', 'Division'), ('subdivision', 'Sub Division'), ('area', 'Area'), ('district', 'District'), ('specialdistrict', 'Special District'), ('zone', 'Zone'), ('parish', 'Parish')], max_length=20),
        ),
    ]
