# Generated by Django 4.2.5 on 2023-09-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClergyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=255, unique=True)),
                ('trg_number', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('telephone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Single Parent', 'Single Parent'), ('Widow', 'Widow')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('nationality', models.CharField(choices=[('Country1', 'Country1'), ('Country2', 'Country2')], max_length=255)),
                ('state_of_origin', models.CharField(choices=[('State1', 'State1'), ('State2', 'State2')], max_length=255)),
                ('local_govt_area', models.CharField(max_length=255)),
            ],
        ),
    ]
