# Generated by Django 4.2.5 on 2024-03-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergydetails',
            name='profile_picture',
            field=models.ImageField(default='parish_pic/Celestial-Church-of-Christ-CCC.jpg', upload_to='parish_pic'),
        ),
        migrations.AlterModelTable(
            name='clergydetails',
            table='clergydetails',
        ),
    ]
