# Generated by Django 4.2.5 on 2023-12-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClergyDetails',
            fields=[
                ('clergy_id', models.AutoField(primary_key=True, serialize=False)),
                ('reg_number', models.IntegerField()),
                ('trg_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('spoken_languages', models.TextField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=50)),
                ('state_of_origin', models.CharField(max_length=50)),
                ('lga_if_nigerian', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=5)),
                ('genotype', models.CharField(max_length=5)),
                ('any_ailment', models.CharField(max_length=3)),
                ('any_disabilities', models.CharField(max_length=3)),
                ('ailment', models.CharField(max_length=50)),
                ('disability', models.CharField(max_length=50)),
                ('permanent_address', models.CharField(max_length=255)),
                ('resident_address', models.CharField(max_length=255)),
                ('parish', models.CharField(max_length=100)),
                ('parish_address', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=255)),
                ('former_religion', models.CharField(max_length=50)),
                ('denomination', models.CharField(max_length=50)),
                ('status_former_religion', models.CharField(max_length=255)),
                ('entry_date_in_ccc', models.DateField()),
                ('first_parish', models.CharField(max_length=255)),
                ('shepherd_who_baptized_you', models.CharField(max_length=255)),
                ('shepherd_who_sanctified_you', models.CharField(max_length=255)),
                ('date_when_baptized', models.DateField()),
                ('parish_where_baptized', models.CharField(max_length=255)),
                ('first_annointment', models.CharField(max_length=50)),
                ('date_of_first_annointment', models.DateField()),
                ('present_annointment', models.CharField(max_length=50)),
                ('date_of_present_annointment', models.DateField()),
                ('edu_level', models.TextField()),
                ('edu_qualification', models.TextField()),
                ('apprenticeship', models.CharField(max_length=255)),
                ('hobbies', models.CharField(max_length=255)),
                ('area_of_calling', models.TextField()),
                ('working_experience_option', models.CharField(max_length=3)),
                ('work_experience_ifyes', models.CharField(max_length=255)),
                ('spouse', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=50)),
                ('mother', models.CharField(max_length=50)),
                ('next_of_kin', models.CharField(max_length=50)),
                ('relation_in_ccc', models.CharField(max_length=50)),
                ('children_info', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'clergydetails',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ClergyForm',
        ),
    ]
