# Generated by Django 4.2.5 on 2024-03-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergydetails',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterModelTable(
            name='clergydetails',
            table='clergydetails',
        ),
    ]
