# Generated by Django 4.2.5 on 2024-03-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0002_alter_clergydetails_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergydetails',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
