# Generated by Django 4.2.5 on 2023-12-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0002_clergydetails_delete_clergyform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clergydetails',
            options={'managed': True},
        ),
    ]
