# Generated by Django 4.2.5 on 2024-05-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0003_annointmentgazzette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annointmentgazzette',
            name='rank',
            field=models.CharField(choices=[('MALE RANK', (('', '--select--'), ('Asst. Elder Bro', 'Asst. Elder Bro'), ('Full. Elder Bro', 'Full. Elder Bro'), ('Cape Elde Bro', 'Cape Elde Bro'), ('Lace Elder Bro', 'Lace Elder Bro'), ('Snr Elder Bro', 'Snr Elder Bro'), ('Sup. Snr. Elder Bro', 'Sup. Snr. Elder Bro'), ('Asst. Leader', 'Asst. Leader'), ('Full Leader', 'Full Leader'), ('Senior Leader', 'Senior Leader'), ('Superior Leader', 'Superior Leader'), ('Superior Snr. Leader', 'Superior Snr. Leader'), ('Asst. Evangelist', 'Asst. Evangelist'), ('Full Evngelist', 'Full Evngelist'), ('Senior Evang', 'Senior Evang'), ('Most Snr. Evangelist', 'Most Snr. Evangelist'), ('Ven. Snr. Evang', 'Ven. Snr. Evang'), ('Asst. Sup Evangelist', 'Asst. Sup Evangelist'), ('Ven. Sup Evang', 'Ven. Sup Evang'), ('Asst. Most Sup Evang', 'Asst. Most Sup Evang'), ('Most Sup Evang', 'Most Sup Evang'))), ('PROPHETS', (('One Cross Prophet', 'One Cross Prophet'), ('Cape Prophet', 'Cape Prophet'), ('Lace Prophet', 'Lace Prophet'), ('Snr Prophet(Wolider)', 'Snr Prophet(Wolider)'), ('Sup Prophet(Wolider)', 'Sup Prophet(Wolider)'), ('Sup. Snr Prophet(Wolider)', 'Sup. Snr Prophet(Wolider)'))), ('FEMALE RANK', (('Asst. Elder Sister', 'Asst. Elder Sister'), ('Elder Sister', 'Elder Sister'), ('Cape Elder Sister', 'Cape Elder Sister'), ('Lace Elder Sister', 'Lace Elder Sister'), ('Snr Elder Sister', 'Snr Elder Sister'), ('Sup. Snr Elder Sister', 'Sup. Snr Elder Sister'), ('lace Sup Elder Sister', 'lace Sup Elder Sister'), ('Lace Sup. Snr Elder Sister', 'Lace Sup. Snr Elder Sister'), ('Mother Celestial', 'Mother Celestial'))), ('PROPHETESS', (('One Cross Prophetess', 'One Cross Prophetess'), ('Cape Prophetess', 'Cape Prophetess'), ('Lace Prophetess', 'Lace Prophetess'), ('Snr Prophetess(Wolima)', 'Snr Prophetess(Wolima)'), ('Sup Prophetess(Wolima)', 'Sup Prophetess(Wolima)'), ('Sup. Snr. Prophetess(Wolima)', 'Sup. Snr. Prophetess(Wolima)')))], error_messages={'required': 'Please select the first annointment.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='first_annointment',
            field=models.CharField(choices=[('MALE RANK', (('', '--select--'), ('Asst. Elder Bro', 'Asst. Elder Bro'), ('Full. Elder Bro', 'Full. Elder Bro'), ('Cape Elde Bro', 'Cape Elde Bro'), ('Lace Elder Bro', 'Lace Elder Bro'), ('Snr Elder Bro', 'Snr Elder Bro'), ('Sup. Snr. Elder Bro', 'Sup. Snr. Elder Bro'), ('Asst. Leader', 'Asst. Leader'), ('Full Leader', 'Full Leader'), ('Senior Leader', 'Senior Leader'), ('Superior Leader', 'Superior Leader'), ('Superior Snr. Leader', 'Superior Snr. Leader'), ('Asst. Evangelist', 'Asst. Evangelist'), ('Full Evngelist', 'Full Evngelist'), ('Senior Evang', 'Senior Evang'), ('Most Snr. Evangelist', 'Most Snr. Evangelist'), ('Ven. Snr. Evang', 'Ven. Snr. Evang'), ('Asst. Sup Evangelist', 'Asst. Sup Evangelist'), ('Ven. Sup Evang', 'Ven. Sup Evang'), ('Asst. Most Sup Evang', 'Asst. Most Sup Evang'), ('Most Sup Evang', 'Most Sup Evang'))), ('PROPHETS', (('One Cross Prophet', 'One Cross Prophet'), ('Cape Prophet', 'Cape Prophet'), ('Lace Prophet', 'Lace Prophet'), ('Snr Prophet(Wolider)', 'Snr Prophet(Wolider)'), ('Sup Prophet(Wolider)', 'Sup Prophet(Wolider)'), ('Sup. Snr Prophet(Wolider)', 'Sup. Snr Prophet(Wolider)'))), ('FEMALE RANK', (('Asst. Elder Sister', 'Asst. Elder Sister'), ('Elder Sister', 'Elder Sister'), ('Cape Elder Sister', 'Cape Elder Sister'), ('Lace Elder Sister', 'Lace Elder Sister'), ('Snr Elder Sister', 'Snr Elder Sister'), ('Sup. Snr Elder Sister', 'Sup. Snr Elder Sister'), ('lace Sup Elder Sister', 'lace Sup Elder Sister'), ('Lace Sup. Snr Elder Sister', 'Lace Sup. Snr Elder Sister'), ('Mother Celestial', 'Mother Celestial'))), ('PROPHETESS', (('One Cross Prophetess', 'One Cross Prophetess'), ('Cape Prophetess', 'Cape Prophetess'), ('Lace Prophetess', 'Lace Prophetess'), ('Snr Prophetess(Wolima)', 'Snr Prophetess(Wolima)'), ('Sup Prophetess(Wolima)', 'Sup Prophetess(Wolima)'), ('Sup. Snr. Prophetess(Wolima)', 'Sup. Snr. Prophetess(Wolima)')))], error_messages={'required': 'Please select the first annointment.'}, max_length=50),
        ),
    ]
