# Generated by Django 4.2.5 on 2023-12-20 08:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0003_alter_clergydetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clergydetails',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='ailment',
            field=models.CharField(blank=True, error_messages={'required': 'Please enter the ailment.'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='any_ailment',
            field=models.CharField(blank=True, choices=[('', 'Select one'), ('Yes', 'Yes'), ('No', 'No')], default='', error_messages={'required': 'Please select an option.'}, max_length=3),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='any_disabilities',
            field=models.CharField(blank=True, choices=[('', 'Select one'), ('Yes', 'Yes'), ('No', 'No')], default='', error_messages={'required': 'Please select an option.'}, max_length=3),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='apprenticeship',
            field=models.CharField(error_messages={'required': 'Please enter the apprenticeship.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='area_of_calling',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Evangelism', 'Evangelism'), ('Shepherdship', 'Shepherdship'), ('Prophecy', 'Prophecy'), ('Teacher', 'Teacher'), ('Church Planting', 'church Planting'), ('Church Addministation', 'Church Administration'), ('Prayer Warroir', 'Prayer Warrior'), ('Choir Ministry', 'Choir Ministry'), ('Marriage Counselling', 'Marriage Counselling'), ('Youth Work', 'Youth Work'), ("Women's Ministrations", "Women's Ministrations"), ('Others', 'Others')], error_messages={'required': 'Please select the area of calling.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('', 'Select one'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', error_messages={'required': 'Please select a blood group.'}, max_length=5),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='children_info',
            field=models.CharField(error_messages={'required': 'Please enter the children info.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='date_of_first_annointment',
            field=models.DateField(error_messages={'required': 'Please enter the date of first annointment.'}),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='date_of_present_annointment',
            field=models.DateField(blank=True, error_messages={'required': 'Please enter the date of present annointment.'}, null=True),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='date_when_baptized',
            field=models.DateField(error_messages={'required': 'Please enter the date when baptized.'}),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='denomination',
            field=models.CharField(error_messages={'required': 'Please enter the denomination.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='disability',
            field=models.CharField(blank=True, error_messages={'required': 'Please enter the disability.'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='edu_level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NONE', 'None'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('College', 'College'), ('Polytechnic', 'Polytechnic'), ('University', 'University'), ('Modern', 'Modern')], error_messages={'required': 'Please select the education level.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='edu_qualification',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NONE', 'None'), ('Primary Leaving Certificate', 'Primary Leaving Certificate'), ('First School Leaving Certificate', 'First School Leaving Certificate'), ('Junior Secondary School Certificate', 'Junior Secondary School Certificate'), ('Senior Secondary School Certificate', 'Senior Secondary School Certificate'), ('National Certificate of Education', 'National Certificate of Education'), ('National Diploma', 'National Diploma'), ('Higher National Diploma', 'Higher National Diploma'), ('Bachelor of Arts', 'Bachelor of Arts'), ('Bachelor of Science', 'Bachelor of Science'), ('Bachelor of Technology', 'Bachelor of Technology'), ('Bachelor of Engineering', 'Bachelor of Engineering'), ('Bachelor of Education', 'Bachelor of Education'), ('Bachelor of Laws', 'Bachelor of Laws'), ('Bachelor of Medicine', 'Bachelor of Medicine'), ('Bachelor of Surgery', 'Bachelor of Surgery'), ('Master of Arts', 'Master of Arts'), ('Master of Science', 'Master of Science'), ('Master of Technology', 'Master of Technology'), ('Master of Engineering', 'Master of Engineering'), ('Master of Education', 'Master of Education'), ('Master of Laws', 'Master of Laws'), ('Master of Medicine', 'Master of Medicine'), ('Master of Surgery', 'Master of Surgery'), ('Doctor of Philosophy', 'Doctor of Philosophy'), ('Doctor of Medicine', 'Doctor of Medicine'), ('Doctor of Surgery', 'Doctor of Surgery'), ('Doctor of Laws', 'Doctor of Laws')], error_messages={'required': 'Please select the education qualification.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='email_address',
            field=models.EmailField(error_messages={'required': 'Please enter the email address.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='entry_date_in_ccc',
            field=models.DateField(error_messages={'required': 'Please enter the entry date in CCC.'}),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='father',
            field=models.CharField(error_messages={'required': 'Please enter the father.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='first_annointment',
            field=models.CharField(choices=[('MALE RANK', (('', '--select--'), ('Asst. Elder Bro', 'Asst. Elder Bro'), ('Full. Elder Bro', 'Full. Elder Bro'), ('Cape Elde Bro', 'Cape Elde Bro'), ('Lace Elder Bro', 'Lace Elder Bro'), ('Snr Elder Bro', 'Snr Elder Bro'), ('Sup. Snr. Elder Brp', 'Sup. Snr. Elder Brp'), ('Asst. Leader', 'Asst. Leader'), ('Full Leader', 'Full Leader'), ('Senior Leader', 'Senior Leader'), ('Superior Leader', 'Superior Leader'), ('Superior Snr. Leader', 'Superior Snr. Leader'), ('Asst. Evangelist', 'Asst. Evangelist'), ('Full Evngelist', 'Full Evngelist'), ('Senior Evang', 'Senior Evang'), ('Most Snr. Evangelist', 'Most Snr. Evangelist'), ('Ven. Snr. Evang', 'Ven. Snr. Evang'), ('Asst. Sup Evangelist', 'Asst. Sup Evangelist'), ('Ven. Sup Evang', 'Ven. Sup Evang'), ('Asst. Most Sup Evang', 'Asst. Most Sup Evang'), ('Most Sup Evang', 'Most Sup Evang'))), ('PROPHETS', (('One Cross Prophet', 'One Cross Prophet'), ('Cape Prophet', 'Cape Prophet'), ('Lace Prophet', 'Lace Prophet'), ('Snr Prophet(Wolider)', 'Snr Prophet(Wolider)'), ('Sup Prophet(Wolider)', 'Sup Prophet(Wolider)'), ('Sup. Snr Prophet(Wolider)', 'Sup. Snr Prophet(Wolider)'))), ('FEMALE RANK', (('Asst. Elder Sister', 'Asst. Elder Sister'), ('Elder Sister', 'Elder Sister'), ('Cape Elder Sister', 'Cape Elder Sister'), ('Lace Elder Sister', 'Lace Elder Sister'), ('Snr Elder Sister', 'Snr Elder Sister'), ('Sup. Snr Elder Sister', 'Sup. Snr Elder Sister'), ('lace Sup Elder Sister', 'lace Sup Elder Sister'), ('Lace Sup. Snr Elder Sister', 'Lace Sup. Snr Elder Sister'), ('Mother Celestial', 'Mother Celestial'))), ('PROPHETESS', (('One Cross Prophetess', 'One Cross Prophetess'), ('Cape Prophetess', 'Cape Prophetess'), ('Lace Prophetess', 'Lace Prophetess'), ('Snr Prophetess(Wolima)', 'Snr Prophetess(Wolima)'), ('Sup Prophetess(Wolima)', 'Sup Prophetess(Wolima)'), ('Sup. Snr. Prophetess(Wolima)', 'Sup. Snr. Prophetess(Wolima)')))], error_messages={'required': 'Please select the first annointment.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='first_parish',
            field=models.CharField(error_messages={'required': 'Please enter the first parish.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='former_religion',
            field=models.CharField(error_messages={'required': 'Please enter the former religion.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Select one'), ('Male', 'Male'), ('Female', 'Female'), ('undefined', 'None')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='genotype',
            field=models.CharField(blank=True, choices=[('', 'Select one'), ('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('SC', 'SC'), ('AC', 'AC'), ('CC', 'CC')], default='', error_messages={'required': 'Please select a genotype.'}, max_length=5),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='hobbies',
            field=models.CharField(error_messages={'required': 'Please enter the hobbies.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='lga_if_nigerian',
            field=models.CharField(error_messages={'required': 'Please enter the LGA if Nigerian.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('', 'Select one'), ('Single', 'Single'), ('Married', 'Married'), ('Single Parent', 'Single Parent'), ('Divorced', 'Divorced'), ('Widow', 'Widow')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='mother',
            field=models.CharField(error_messages={'required': 'Please enter the mother.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='nationality',
            field=models.CharField(choices=[('Nigeria', 'Nigeria'), ('Ghana', 'Ghana'), ('Benin Republic', 'Benin Republic'), ('Togo', 'Togo'), ('Cameroon', 'Cameroon'), ('Ivory Coast', 'Ivory Coast'), ('Liberia', 'Liberia'), ('Sierra Leone', 'Sierra Leone'), ('Guinea', 'Guinea'), ('Guinea Bissau', 'Guinea Bissau'), ('Senegal', 'Senegal'), ('Mali', 'Mali'), ('Burkina Faso', 'Burkina Faso'), ('Niger', 'Niger'), ('Chad', 'Chad'), ('Central African Republic', 'Central African Republic'), ('Sudan', 'Sudan'), ('South Sudan', 'South Sudan'), ('Ethiopia', 'Ethiopia'), ('Eritrea', 'Eritrea'), ('Somalia', 'Somalia'), ('Djibouti', 'Djibouti'), ('Kenya', 'Kenya'), ('Uganda', 'Uganda'), ('Rwanda', 'Rwanda'), ('Burundi', 'Burundi'), ('Tanzania', 'Tanzania'), ('Zambia', 'Zambia'), ('Malawi', 'Malawi'), ('Mozambique', 'Mozambique'), ('Zimbabwe', 'Zimbabwe'), ('Angola', 'Angola'), ('Namibia', 'Namibia'), ('Botswana', 'Botswana'), ('South Africa', 'South Africa'), ('Lesotho', 'Lesotho'), ('Swaziland', 'Swaziland'), ('Madagascar', 'Madagascar'), ('Mauritius', 'Mauritius'), ('Seychelles', 'Seychelles'), ('Comoros', 'Comoros'), ('Mauritania', 'Mauritania'), ('Western Sahara', 'Western Sahara'), ('Morocco', 'Morocco'), ('Algeria', 'Algeria'), ('Tunisia', 'Tunisia'), ('Libya', 'Libya'), ('Egypt', 'Egypt'), ('Gambia', 'Gambia'), ('Greece', 'Greece'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('Portugal', 'Portugal'), ('France', 'France'), ('Germany', 'Germany'), ('Belgium', 'Belgium'), ('Netherlands', 'Netherlands'), ('Luxembourg', 'Luxembourg'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Czech Republic', 'Czech Republic'), ('Slovakia', 'Slovakia'), ('Hungary', 'Hungary'), ('Slovenia', 'Slovenia'), ('Croatia', 'Croatia'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Serbia', 'Serbia'), ('Montenegro', 'Montenegro'), ('Albania', 'Albania'), ('Macedonia', 'Macedonia'), ('Bulgaria', 'Bulgaria'), ('Romania', 'Romania'), ('Moldova', 'Moldova'), ('Ukraine', 'Ukraine'), ('Belarus', 'Belarus'), ('Poland', 'Poland'), ('Lithuania', 'Lithuania'), ('Latvia', 'Latvia'), ('Estonia', 'Estonia'), ('Finland', 'Finland'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Denmark', 'Denmark'), ('Iceland', 'Iceland'), ('Ireland', 'Ireland'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('United States', 'United States'), ('Mexico', 'Mexico'), ('Greenland', 'Greenland'), ('Cuba', 'Cuba'), ('Haiti', 'Haiti'), ('Dominican Republic', 'Dominican Republic'), ('Guatemala', 'Guatemala'), ('Belize', 'Belize'), ('El Salvador', 'El Salvador'), ('Honduras', 'Honduras'), ('Nicaragua', 'Nicaragua'), ('Costa Rica', 'Costa Rica'), ('Panama', 'Panama'), ('Colombia', 'Colombia'), ('Venezuela', 'Venezuela'), ('Peru', 'Peru')], error_messages={'required': 'Please select a country.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='next_of_kin',
            field=models.CharField(error_messages={'required': 'Please enter the next of kin.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='parish',
            field=models.CharField(error_messages={'required': 'Please enter the parish.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='parish_address',
            field=models.CharField(error_messages={'required': 'Please enter the parish address.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='parish_where_baptized',
            field=models.CharField(error_messages={'required': 'Please enter the parish where baptized.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='permanent_address',
            field=models.CharField(error_messages={'required': 'Please enter the permanent address.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='present_annointment',
            field=models.CharField(choices=[('MALE RANK', (('', '--select--'), ('Asst. Elder Bro', 'Asst. Elder Bro'), ('Full. Elder Bro', 'Full. Elder Bro'), ('Cape Elde Bro', 'Cape Elde Bro'), ('Lace Elder Bro', 'Lace Elder Bro'), ('Snr Elder Bro', 'Snr Elder Bro'), ('Sup. Snr. Elder Bro', 'Sup. Snr. Elder Bro'), ('Asst. Leader', 'Asst. Leader'), ('Full Leader', 'Full Leader'), ('Senior Leader', 'Senior Leader'), ('Superior Leader', 'Superior Leader'), ('Superior Snr. Leader', 'Superior Snr. Leader'), ('Asst. Evangelist', 'Asst. Evangelist'), ('Full Evangelist', 'Full Evngelist'), ('Senior Evang', 'Senior Evang'), ('Most Snr. Evangelist', 'Most Snr. Evangelist'), ('Ven. Snr. Evang', 'Ven. Snr. Evang'), ('Asst. Sup Evangelist', 'Asst. Sup Evangelist'), ('Ven. Sup Evang', 'Ven. Sup Evang'), ('Asst. Most Sup Evang', 'Asst. Most Sup Evang'), ('Most Sup Evang', 'Most Sup Evang'))), ('PROPHETS', (('One Cross Prophet', 'One Cross Prophet'), ('Cape Prophet', 'Cape Prophet'), ('Lace Prophet', 'Lace Prophet'), ('Snr Prophet(Wolider)', 'Snr Prophet(Wolider)'), ('Sup Prophet(Wolider)', 'Sup Prophet(Wolider)'), ('Sup. Snr Prophet(Wolider)', 'Sup. Snr Prophet(Wolider)'))), ('FEMALE RANK', (('Asst. Elder Sister', 'Asst. Elder Sister'), ('Elder Sister', 'Elder Sister'), ('Cape Elder Sister', 'Cape Elder Sister'), ('Lace Elder Sister', 'Lace Elder Sister'), ('Snr Elder Sister', 'Snr Elder Sister'), ('Sup. Snr Elder Sister', 'Sup. Snr Elder Sister'), ('lace Sup Elder Sister', 'lace Sup Elder Sister'), ('Lace Sup. Snr Elder Sister', 'Lace Sup. Snr Elder Sister'), ('Mother Celestial', 'Mother Celestial'))), ('PROPHETESS', (('One Cross Prophetess', 'One Cross Prophetess'), ('Cape Prophetess', 'Cape Prophetess'), ('Lace Prophetess', 'Lace Prophetess'), ('Snr Prophetess(Wolima)', 'Snr Prophetess(Wolima)'), ('Sup Prophetess(Wolima)', 'Sup Prophetess(Wolima)'), ('Sup. Snr. Prophetess(Wolima)', 'Sup. Snr. Prophetess(Wolima)')))], error_messages={'required': 'Please select the present annointment.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='relation_in_ccc',
            field=models.CharField(error_messages={'required': 'Please enter the relation in CCC.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='resident_address',
            field=models.CharField(error_messages={'required': 'Please enter the resident address.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='shepherd_who_baptized_you',
            field=models.CharField(error_messages={'required': 'Please enter the shepherd who baptized you.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='shepherd_who_sanctified_you',
            field=models.CharField(error_messages={'required': 'Please enter the shepherd who sanctified you.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='spoken_languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('French', 'French'), ('Yoruba', 'Yoruba'), ('Igbo', 'Igbo'), ('Hausa', 'Hausa'), ('French', 'French'), ('Egun', 'Egun'), ('Dutch', 'Dutch'), ('Pidgin', 'Pidgin'), ('Arabic', 'Arabic')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='spouse',
            field=models.CharField(error_messages={'required': 'Please enter the spouse.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='state_of_origin',
            field=models.CharField(error_messages={'required': 'Please enter the state of origin.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='status_former_religion',
            field=models.CharField(error_messages={'required': 'Please enter the status of former religion.'}, max_length=255),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='telephone',
            field=models.CharField(error_messages={'required': 'Please enter the telephone number.'}, max_length=20),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='work_experience_ifyes',
            field=models.CharField(blank=True, error_messages={'required': 'Please enter the work experience if yes.'}, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='working_experience_option',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], error_messages={'required': 'Please select an option.'}, max_length=3),
        ),
    ]
