# Generated by Django 4.2.5 on 2025-09-11 13:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0004_alter_annointmentgazzette_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergydetails',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'required': 'Please enter the telephone number.'}, max_length=128, region='NG'),
        ),
    ]
