# Generated by Django 4.2.5 on 2023-12-27 13:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0004_remove_clergydetails_country_and_more'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='clergydetails',
            name='area_of_calling',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Evangelism', 'Evangelism'), ('Shepherdship', 'Shepherdship'), ('Prophecy', 'Prophecy'), ('Teacher', 'Teacher'), ('Church Planting', 'church Planting'), ('Church Addministation', 'Church Administration'), ('Prayer Warroir', 'Prayer Warrior'), ('Choir Ministry', 'Choir Ministry'), ('Marriage Counselling', 'Marriage Counselling'), ('Youth Work', 'Youth Work'), ("Women's Ministrations", "Women's Ministrations"), ('Others', 'Others')], error_messages={'required': 'Please select the area of calling.'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='edu_level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NONE', 'None'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('College', 'College'), ('Polytechnic', 'Polytechnic'), ('University', 'University'), ('Modern', 'Modern')], error_messages={'required': 'Please select the education level.'}, max_length=250),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='edu_qualification',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NONE', 'None'), ('Primary Leaving Certificate', 'Primary Leaving Certificate'), ('First School Leaving Certificate', 'First School Leaving Certificate'), ('Junior Secondary School Certificate', 'Junior Secondary School Certificate'), ('Senior Secondary School Certificate', 'Senior Secondary School Certificate'), ('National Certificate of Education', 'National Certificate of Education'), ('National Diploma', 'National Diploma'), ('Higher National Diploma', 'Higher National Diploma'), ('Bachelor of Arts', 'Bachelor of Arts'), ('Bachelor of Science', 'Bachelor of Science'), ('Bachelor of Technology', 'Bachelor of Technology'), ('Bachelor of Engineering', 'Bachelor of Engineering'), ('Bachelor of Education', 'Bachelor of Education'), ('Bachelor of Laws', 'Bachelor of Laws'), ('Bachelor of Medicine', 'Bachelor of Medicine'), ('Bachelor of Surgery', 'Bachelor of Surgery'), ('Master of Arts', 'Master of Arts'), ('Master of Science', 'Master of Science'), ('Master of Technology', 'Master of Technology'), ('Master of Engineering', 'Master of Engineering'), ('Master of Education', 'Master of Education'), ('Master of Laws', 'Master of Laws'), ('Master of Medicine', 'Master of Medicine'), ('Master of Surgery', 'Master of Surgery'), ('Doctor of Philosophy', 'Doctor of Philosophy'), ('Doctor of Medicine', 'Doctor of Medicine'), ('Doctor of Surgery', 'Doctor of Surgery'), ('Doctor of Laws', 'Doctor of Laws')], error_messages={'required': 'Please select the education qualification.'}, max_length=1000),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='profile_picture',
            field=models.ImageField(default='static/assets/img/User/circled_user_male_skin_type_5_480px.png', upload_to='clergy_registration/profile_pics'),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='spoken_languages',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('French', 'French'), ('Yoruba', 'Yoruba'), ('Igbo', 'Igbo'), ('Hausa', 'Hausa'), ('French', 'French'), ('Egun', 'Egun'), ('Dutch', 'Dutch'), ('Pidgin', 'Pidgin'), ('Arabic', 'Arabic')], max_length=100),
        ),
    ]
