# Generated by Django 4.2.5 on 2024-02-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0005_remove_clergydetails_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergydetails',
            name='any_ailment',
            field=models.CharField(choices=[('', 'Select one'), ('Yes', 'Yes'), ('No', 'No')], default='', error_messages={'required': 'Please select an option.'}, max_length=3),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='any_disabilities',
            field=models.CharField(choices=[('', 'Select one'), ('Yes', 'Yes'), ('No', 'No')], default='', error_messages={'required': 'Please select an option.'}, max_length=3),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='denomination',
            field=models.CharField(blank=True, error_messages={'required': 'Please enter the denomination.'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='former_religion',
            field=models.CharField(blank=True, error_messages={'required': 'Please enter the former religion.'}, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='gender',
            field=models.CharField(choices=[('', 'Select one'), ('Male', 'Male'), ('Female', 'Female'), ('undefined', 'None')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='genotype',
            field=models.CharField(choices=[('', 'Select one'), ('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('SC', 'SC'), ('AC', 'AC'), ('CC', 'CC')], default='', error_messages={'required': 'Please select a genotype.'}, max_length=5),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='marital_status',
            field=models.CharField(choices=[('', 'Select one'), ('Single', 'Single'), ('Married', 'Married'), ('Single Parent', 'Single Parent'), ('Divorced', 'Divorced'), ('Widow', 'Widow')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='status_former_religion',
            field=models.CharField(blank=True, error_messages={'required': 'Please enter the status of former religion.'}, max_length=255, null=True),
        ),
    ]
