# Generated by Django 4.2.5 on 2025-09-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0006_alter_annointmentgazzette_annoiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergydetails',
            name='gender',
            field=models.CharField(choices=[('', 'Select one'), ('Male', 'Male'), ('Female', 'Female'), ('undefined', 'None')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clergydetails',
            name='marital_status',
            field=models.CharField(choices=[('', 'Select one'), ('Single', 'Single'), ('Married', 'Married'), ('Single Parent', 'Single Parent'), ('Divorced', 'Divorced'), ('Widow', 'Widow')], default='', max_length=20, null=True),
        ),
    ]
