# Generated by Django 4.2.5 on 2024-02-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0006_remove_clergydetails_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clergydetails',
            name='country',
        ),
    ]
