# Generated by Django 4.2.5 on 2025-09-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0007_alter_clergydetails_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergydetails',
            name='blood_group',
            field=models.CharField(choices=[('', 'Select one'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='', error_messages={'required': 'Please select a blood group.'}, max_length=5, null=True),
        ),
    ]
