# Generated by Django 4.2.5 on 2025-09-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0008_alter_clergydetails_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clergydetails',
            name='reg_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
