# Generated by Django 4.2.5 on 2024-05-01 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clergy_registration', '0004_alter_annointmentgazzette_rank_and_more'),
        ('ParishRestructure', '0010_alter_location_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfered', models.DateField()),
                ('trf_begin', models.DateField()),
                ('trf_end', models.DateField()),
                ('trf_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Withdrawn', 'Withdrawn')], max_length=50)),
                ('trf_extended', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('clergy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clergy_registration.clergydetails')),
                ('parishFrm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parishFrm', to='ParishRestructure.parishrestructure')),
                ('parishTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parishTo', to='ParishRestructure.parishrestructure')),
            ],
            options={
                'db_table': 'transfer_data',
            },
        ),
        migrations.CreateModel(
            name='PostingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('Head of Diocese', 'Head of Diocese'), ('State Evangelist', 'State Evangelist'), ('Regional Evangelist', 'Regional Evangelist'), ('Divisional Evangelist', 'Divisional Evangelist'), ('Area Evangelist', 'Area Evangelist'), ('District Evangelist', 'District Evangelist'), ('Zonal Evangelist', 'Zonal Evangelist'), ('Shepherd in Charge', 'Shepherd in Charge'), ('Assistant Shepherd', 'Assitant Shepherd'), ('Church Worker', 'Church Worker'), ('Church Prophet/ess', 'Church Prophet/ess')], max_length=50)),
                ('date_of_entry', models.DateField()),
                ('date_of_exit', models.DateField()),
                ('purpose', models.CharField(max_length=250)),
                ('clergy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clergy_registration.clergydetails')),
                ('parish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParishRestructure.parishdirectory')),
            ],
            options={
                'db_table': 'posting_history',
            },
        ),
        migrations.CreateModel(
            name='ClergyTrfbio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floating', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('clergy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clergy_registration.clergydetails')),
            ],
            options={
                'db_table': 'clergy_trfbio',
            },
        ),
    ]
