# Generated by Django 4.2.5 on 2024-05-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdata',
            name='extended_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferdata',
            name='date_transfered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
