# Generated by Django 4.2.5 on 2024-05-09 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ParishRestructure', '0010_alter_location_level'),
        ('transfer', '0002_transferdata_extended_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferdata',
            name='designation_frm',
            field=models.CharField(blank=True, choices=[('Head of Diocese', 'Head of Diocese'), ('State Evangelist', 'State Evangelist'), ('Regional Evangelist', 'Regional Evangelist'), ('Divisional Evangelist', 'Divisional Evangelist'), ('Area Evangelist', 'Area Evangelist'), ('District Evangelist', 'District Evangelist'), ('Zonal Evangelist', 'Zonal Evangelist'), ('Shepherd in Charge', 'Shepherd in Charge'), ('Assistant Shepherd', 'Assitant Shepherd'), ('Church Worker', 'Church Worker'), ('Church Prophet/ess', 'Church Prophet/ess')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transferdata',
            name='designation_to',
            field=models.CharField(blank=True, choices=[('Head of Diocese', 'Head of Diocese'), ('State Evangelist', 'State Evangelist'), ('Regional Evangelist', 'Regional Evangelist'), ('Divisional Evangelist', 'Divisional Evangelist'), ('Area Evangelist', 'Area Evangelist'), ('District Evangelist', 'District Evangelist'), ('Zonal Evangelist', 'Zonal Evangelist'), ('Shepherd in Charge', 'Shepherd in Charge'), ('Assistant Shepherd', 'Assitant Shepherd'), ('Church Worker', 'Church Worker'), ('Church Prophet/ess', 'Church Prophet/ess')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transferdata',
            name='parishFrm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parishFrm', to='ParishRestructure.parishrestructure'),
        ),
        migrations.AlterField(
            model_name='transferdata',
            name='parishTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parishTo', to='ParishRestructure.parishrestructure'),
        ),
    ]
