# Generated by Django 4.2.5 on 2024-05-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0004_alter_annointmentgazzette_rank_and_more'),
        ('transfer', '0003_transferdata_designation_frm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clergytrfbio',
            name='note',
        ),
        migrations.AlterField(
            model_name='clergytrfbio',
            name='clergy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clergy_registration.clergydetails'),
        ),
        migrations.AlterField(
            model_name='clergytrfbio',
            name='floating',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transferdata',
            name='clergy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clergy_registration.clergydetails'),
        ),
    ]
