# Generated by Django 4.2.5 on 2024-05-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clergy_registration', '0004_alter_annointmentgazzette_rank_and_more'),
        ('transfer', '0005_alter_clergytrfbio_clergy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postinghistory',
            name='clergy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clergy_registration.clergydetails'),
        ),
        migrations.AlterField(
            model_name='postinghistory',
            name='purpose',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='transferdata',
            name='date_transfered',
            field=models.DateField(),
        ),
    ]
